-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQge4wgzhswyUyhacmf
wt74PoqoDIOTP6XXp05T7zqkmMWgCgYIKoZIzj0DAQehRANCAAT2UkFQRRBpqR48
rOxA4NhIgxqQqc0T0QrHRfbAGHZfMMXwFuACghGJY6rAtJ/So+Yiycnot6EanbPH
WAa8jFsB
-----END PRIVATE KEY-----